version: '3'

services:
    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
         - "80:80"
         - "443:443"
        volumes:
         - ./volumes/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
         - ./volumes/nginx/etc/letsencrypt:/etc/letsencrypt
         - ./volumes/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
    portainer:
        image: portainer/portainer
        container_name: portainer
        restart: unless-stopped
        volumes:
         - ./volumes/portainer/data:/data
         - /var/run/docker.sock:/var/run/docker.sock
networks:
    default:
        external:
            name: backend
